export const journalCategories = [
  "Branding",
  "Posicionamento",
  "Imagem",
  "Design",
  "Marketing",
  "Vendas",
  "Negócios",
  "Tendências",
  "Conversas",
];

export const journalArticles = [
  {
    id: "journal-daniela-001",
    slug: "ainda-vale-a-pena-ser-designer-em-2026",
    title: "Ainda vale a pena ser designer em 2026?",
    subtitle: "Minha opinião após quatro anos vivendo essa profissão.",
    description: "Daniela Escatalini reflete sobre carreira, inteligência artificial, valorização e o futuro do design após quatro anos vivendo a profissão.",
    category: "Design",
    tags: ["Design", "Carreira", "Inteligência Artificial", "Branding", "Negócios"],
    date: "2026-06-29",
    displayDate: "29 de junho de 2026",
    readingTime: "18 min de leitura",
    author: "Daniela Escatalini",
    authorRole: "Brand Strategist & Creative Director",
    authorImage: "/assets/journal/daniela-escatalini-colunista-the-revee-journal.jpg",
    authorInstagram: "https://www.instagram.com/daniescatalini",
    authorLinkedin: "https://www.linkedin.com/in/danielaescatalini/",
    coverImage: "/assets/journal/revee-journal-ainda-vale-a-pena-ser-designer-2026.jpg",
    socialImage: "/assets/journal/revee-journal-ainda-vale-a-pena-ser-designer-2026-social.jpg",
    coverAlt: "Mãos de Daniela Escatalini trabalhando em um projeto de design no notebook para matéria do The Revee Journal",
    contentFile: "src/content/journal/ainda-vale-a-pena-ser-designer-em-2026.md",
    featured: true,
    trending: true,
    type: "article",
  },
  {
    id: "journal-erica-001",
    slug: "fotografia-crescimento-profissional",
    title: "Por que a fotografia é tão importante para o seu crescimento profissional?",
    subtitle: "Uma reflexão sobre imagem, posicionamento e coragem de se enxergar.",
    description: "Erica Camargo reflete sobre a fotografia profissional como ferramenta de posicionamento, autopercepção e crescimento para marcas pessoais e negócios.",
    category: "Imagem",
    tags: ["Imagem", "Fotografia", "Posicionamento", "Marca pessoal", "Negócios"],
    date: "2026-07-14",
    displayDate: "14 de julho de 2026",
    readingTime: "5 min de leitura",
    author: "Erica Camargo",
    authorRole: "Fotógrafa",
    authorCompany: "Erica Camargo Fotografia",
    authorImage: "/assets/journal/erica-camargo-fotografa.jpg",
    authorInstagram: "https://www.instagram.com/ericacamargofotografia",
    authorEmail: "Contato@ericacamargo.com.br",
    authorWhatsApp: "https://wa.me/5511968425878",
    authorBio: "Fotógrafa especializada em retratos profissionais, posicionamento de imagem e ensaios com essência, estratégia e conexão.",
    coverImage: "/assets/journal/revee-journal-fotografia-crescimento-profissional.jpg",
    socialImage: "/assets/journal/revee-journal-fotografia-crescimento-profissional-social.jpg",
    coverAlt: "Erica Camargo em retrato profissional ao ar livre, usando blazer bege em cenário natural",
    contentFile: "src/content/journal/fotografia-crescimento-profissional.md",
    featured: true,
    trending: true,
    type: "article",
  },
];
